import { mkdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';

import type * as Prettier from 'prettier';

import type { ConnectionInfo } from './analyze';
import { analyze } from './analyze';
import { emitChannels, emitChannelsDeclaration } from './emit-channels';
import { declareType, emitSchemas } from './emit-types';
import { emitZod, emitZodDeclaration } from './emit-zod';
import { camelCase, pascalCase } from './naming';
import type { ReuseOptions } from './reuse';
import { renderImports, renderReexports, resolveReuse } from './reuse';
import type { AsyncAPIDocument, JsonSchema } from './schema';

const HEADER = `// Generated by @chanx-js/codegen. Do not edit.\n// Regenerate with: npx @chanx-js/codegen\n\n`;

export interface GenerateOptions extends ReuseOptions {
  outDir: string;
  /** Also emit zod schemas and wire them into the descriptors' validators. */
  validation?: 'none' | 'zod';
  /** Emit a file asserting reused types still match the schema. */
  reuseStrict?: boolean;
  /**
   * `ts` writes one typed module per concern. `js` splits each into a runtime `.js` and
   * a `.d.ts`, so a plain JavaScript project can import the descriptors and still get
   * narrowing from its editor.
   */
  emit?: 'ts' | 'js';
  format?: boolean;
}

export interface GenerateResult {
  files: string[];
  generatedTypes: number;
  reusedTypes: string[];
  channels: number;
  topics: number;
}

async function maybeFormat(
  code: string,
  filePath: string,
  enabled: boolean,
): Promise<string> {
  if (!enabled) return code;
  let prettier: typeof Prettier;
  try {
    prettier = await import('prettier');
  } catch {
    // Prettier is an optional peer; unformatted output is still valid.
    return code;
  }
  // A formatting failure means the generated code does not parse: never hide that.
  const config = await prettier.resolveConfig(filePath);
  return prettier.format(code, { ...config, filepath: filePath });
}

/**
 * Fail before writing anything if two schema elements would emit the same identifier.
 * Names are derived by case conversion, so `chat-room` and `chat_room` both become
 * `ChatRoom`, and the output would not compile.
 */
function checkNames(connections: ConnectionInfo[], schemaNames: string[]): void {
  const problems: string[] = [];
  const claim = (owners: Map<string, string>, name: string, owner: string) => {
    const existing = owners.get(name);
    if (existing === undefined) owners.set(name, owner);
    else if (existing !== owner) {
      problems.push(`"${name}" would be emitted for both ${existing} and ${owner}`);
    }
  };

  const identifiers = new Map<string, string>([['channels', 'the channel registry']]);
  for (const name of schemaNames) {
    claim(identifiers, name, `schema ${name}`);
    claim(identifiers, `${name}Schema`, `schema ${name}`);
  }
  for (const connection of connections) {
    claim(identifiers, camelCase(connection.name), `channel "${connection.key}"`);
    const topicKeys = new Map<string, string>();
    for (const channel of [connection, ...connection.topics]) {
      const owner = `channel "${channel.key}"`;
      const prefix = pascalCase(channel.name);
      for (const suffix of ['ToServer', 'ToClient', 'ToServerSchema', 'ToClientSchema']) {
        claim(identifiers, prefix + suffix, owner);
      }
    }
    for (const topic of connection.topics) {
      claim(
        topicKeys,
        camelCase(topic.topic?.name ?? topic.name),
        `channel "${topic.key}"`,
      );
    }
  }

  if (problems.length) {
    throw new Error(
      `Generated names would clash:\n  ${problems.join('\n  ')}\n` +
        'Rename the channels, topics or schemas on the server.',
    );
  }
}

function emitReuseCheck(
  reusedNames: string[],
  schemas: Record<string, JsonSchema>,
  imports: Map<string, Set<string>>,
): string {
  const declarations = reusedNames
    .map((name) => declareType(`Generated${name}`, schemas[name] as JsonSchema))
    .join('\n');

  const assertions = reusedNames
    .map(
      (name) =>
        `export type Check${name} = Assert<MutuallyAssignable<${name}, Generated${name}>>;`,
    )
    .join('\n');

  return (
    HEADER +
    '// Each assertion fails to compile if a reused type has drifted from the schema.\n' +
    '// Reusing a type assumes the name and the shape both still match.\n\n' +
    renderImports(imports) +
    // Purely type-level, so this file works as a .d.ts for JavaScript output too.
    'type MutuallyAssignable<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;\n' +
    'type Assert<T extends true> = T;\n\n' +
    declarations +
    '\n' +
    assertions +
    '\n'
  );
}

export async function generate(
  document: AsyncAPIDocument,
  options: GenerateOptions,
): Promise<GenerateResult> {
  const target = options.emit ?? 'ts';
  if (target !== 'ts' && target !== 'js') {
    throw new Error(`emit must be "ts" or "js", got "${String(target)}"`);
  }
  const validation = options.validation ?? 'none';
  if (validation !== 'none' && validation !== 'zod') {
    throw new Error(`validation must be "none" or "zod", got "${String(validation)}"`);
  }

  const outDir = resolve(options.outDir);
  const schemas = document.components?.schemas ?? {};
  const connections = analyze(document);
  checkNames(connections, Object.keys(schemas));
  const format = options.format ?? true;
  const withZod = validation === 'zod';

  const reuse = await resolveReuse(new Set(Object.keys(schemas)), outDir, options);
  const reusedNames = [...reuse.skip].sort();

  await mkdir(outDir, { recursive: true });
  const files: string[] = [];

  const write = async (name: string, code: string) => {
    const filePath = join(outDir, name);
    await writeFile(filePath, await maybeFormat(code, filePath, format), 'utf-8');
    files.push(filePath);
  };

  const isJs = target === 'js';

  // Message types have no runtime, so in JS mode they are declarations only.
  await write(
    isJs ? 'schemas.d.ts' : 'schemas.ts',
    HEADER +
      renderImports(reuse.imports) +
      renderReexports(reuse.imports) +
      emitSchemas(schemas, reuse.skip),
  );

  const messageNames = [
    ...new Set(
      connections.flatMap((connection) =>
        [connection, ...connection.topics].flatMap((channel) => [
          ...channel.toServer,
          ...channel.toClient,
        ]),
      ),
    ),
  ];

  const channelOptions = {
    withZod,
    schemasModule: './schemas',
    // Node's ESM resolution needs the extension on a real runtime import.
    zodModule: isJs ? './schemas.zod.js' : './schemas.zod',
    target,
  } as const;

  await write(
    isJs ? 'channels.js' : 'channels.ts',
    HEADER + emitChannels(connections, messageNames, channelOptions),
  );
  if (isJs) {
    await write(
      'channels.d.ts',
      HEADER + emitChannelsDeclaration(connections, messageNames, channelOptions),
    );
  }

  if (withZod) {
    await write(
      isJs ? 'schemas.zod.js' : 'schemas.zod.ts',
      HEADER + emitZod(schemas, connections, reuse.skip),
    );
    if (isJs) {
      await write(
        'schemas.zod.d.ts',
        HEADER +
          emitZodDeclaration(schemas, connections, reuse.skip, './schemas', './channels'),
      );
    }
  }

  if (options.reuseStrict && reusedNames.length) {
    await write(
      isJs ? 'reuse-check.d.ts' : 'reuse-check.ts',
      emitReuseCheck(reusedNames, schemas, reuse.imports),
    );
  }

  if (isJs) {
    // `schemas` is types only, so it has nothing to re-export at runtime.
    const runtime = ["export * from './channels.js';"];
    if (withZod) runtime.push("export * from './schemas.zod.js';");
    await write('index.js', HEADER + runtime.join('\n') + '\n');

    const declarations = ["export * from './schemas';", "export * from './channels';"];
    if (withZod) declarations.push("export * from './schemas.zod';");
    await write('index.d.ts', HEADER + declarations.join('\n') + '\n');
  } else {
    const exports = ["export * from './schemas';", "export * from './channels';"];
    if (withZod) exports.push("export * from './schemas.zod';");
    await write('index.ts', HEADER + exports.join('\n') + '\n');
  }

  return {
    files,
    generatedTypes: Object.keys(schemas).length - reuse.skip.size,
    reusedTypes: reusedNames,
    channels: connections.length,
    topics: connections.reduce(
      (total, connection) => total + connection.topics.length,
      0,
    ),
  };
}
