import { defineConfig } from 'vitepress';

// Generated by TypeDoc before every build, so the API reference cannot drift from the code.
import apiSidebar from '../api/typedoc-sidebar.json';

const repo = 'https://github.com/huynguyengl99/chanx-js';

export default defineConfig({
  title: 'chanx-js',
  description:
    'Type-safe WebSocket client for chanx AsyncAPI schemas, with topic multiplexing.',
  base: '/chanx-js/',
  cleanUrls: true,
  head: [['meta', { name: 'theme-color', content: '#3f51b5' }]],
  themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide/getting-started', activeMatch: '/guide/' },
      { text: 'Frameworks', link: '/frameworks/react', activeMatch: '/frameworks/' },
      { text: 'API', link: '/api/', activeMatch: '/api/' },
      { text: 'Design', link: '/design' },
      {
        text: 'Ecosystem',
        items: [
          { text: 'chanx', link: 'https://github.com/huynguyengl99/chanx' },
          { text: 'chanx-kit', link: 'https://huynguyengl99.github.io/chanx-kit/' },
        ],
      },
    ],
    sidebar: {
      '/guide/': [
        {
          text: 'Guide',
          items: [
            { text: 'Getting started', link: '/guide/getting-started' },
            { text: 'Code generation', link: '/guide/codegen' },
            { text: 'Connections', link: '/guide/connections' },
            { text: 'Topics', link: '/guide/topics' },
            { text: 'Delivery modes', link: '/guide/delivery' },
            { text: 'Sharing and closing', link: '/guide/sharing' },
          ],
        },
      ],
      '/frameworks/': [
        {
          text: 'Frameworks',
          items: [
            { text: 'React', link: '/frameworks/react' },
            { text: 'Vue', link: '/frameworks/vue' },
            { text: 'Svelte', link: '/frameworks/svelte' },
            { text: 'Solid', link: '/frameworks/solid' },
            { text: 'Plain JS and Node', link: '/frameworks/vanilla' },
          ],
        },
      ],
      '/api/': [{ text: 'API reference', items: apiSidebar }],
    },
    search: { provider: 'local' },
    editLink: { pattern: `${repo}/edit/main/docs/:path`, text: 'Edit this page' },
    socialLinks: [
      { icon: 'github', link: repo },
      { icon: 'npm', link: 'https://www.npmjs.com/package/@chanx-js/client' },
    ],
    footer: { message: 'MIT licensed' },
    outline: [2, 3],
  },
});
